export enum TransactionTypes {
  Fee = "Fee",
  Trade = "Trade",
  Other = "Other",
  Reverse = "Reverse",
  Hold = "Hold",
  Rebate = "Rebate",
  MarginAcquisition = "MarginAcquisition",
  MarginRelinquishByTrade = "MarginRelinquishByTrade",
  MarginInterestTransfer = "MarginInterestTransfer",
  MarginOperatorTransferToMarginAccount = "MarginOperatorTransferToMarginAccount",
  MarginOperatorTransferToAssetAccount = "MarginOperatorTransferToAssetAccount",
  MarginUserTransfer = "MarginUserTransfer",
  MarginRelinquishByTransfer = "MarginRelinquishByTransfer",
  MarginRelinquishByReverseTrade = "MarginRelinquishByReverseTrade",
  Distribution = "Distribution",
  Payment = "Payment",
  OperatorLend = "OperatorLend",
  OperatorReceived = "OperatorReceived",
  Rebalance = "Rebalance",
  Commission = "Commission",
  AirDrop = "AirDrop"
}
